apiVersion: v1
kind: Service
metadata:
  name: <CONTAINER>
  labels:
    app: <CONTAINER>
spec:
  type: ClusterIP
  ports:
    - name: php-fpm
      protocol: TCP
      port: 9000
  selector:
    run: <CONTAINER>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <CONTAINER>
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      run: <CONTAINER>
  replicas: 1
  template:
    metadata:
      labels:
        run: <CONTAINER>
    spec:
      containers:
        - name: <CONTAINER>
          image: <REGISTRY>/<CONTAINER>:<VERSION>
          ports:
            - containerPort: 9000
      imagePullSecrets:
        - name: <REGISTRY_SECRET>