apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: exosuite-vsftpd
  labels:
    app: exosuite-vsftpd
spec:
  type: ClusterIP
  ports:
    - port: 21
      name: vsftpd-control
  selector:
    app: exosuite-vsftpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: exosuite-vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exosuite-vsftpd
  template:
    metadata:
      labels:
        app: exosuite-vsftpd
    spec:
      containers:
        - name: exosuite-vsftpd
          image: fauria/vsftpd
          ports:
            - containerPort: 21
              protocol: TCP
              name: "ftp-server"
          volumeMounts:
            - mountPath: "/home/vsftpd"
              name: exosuite-vsftpd-claim
          env:
            - name: FTP_USER
              value: "exosuite"
            - name: FTP_PASS
              value: "aUxDF94ALY2YWrTpxhc5gs8"
      nodeSelector:
        type: exosuite-kvm
      volumes:
        - name: exosuite-vsftpd-volume
          persistentVolumeClaim:
            claimName: exosuite-vsftpd-claim
---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: staging
  name: exosuite-vsftpd-volume
  labels:
    type: local
    app: exosuite-vsftpd
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - exosuite-kvm
  storageClassName: local-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/exosuite-vsftpd"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: staging
  name: exosuite-vsftpd-claim
  labels:
    app: exosuite-vsftpd
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
