apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ENV>
  name: <CONTAINER>
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      run: <CONTAINER>
  replicas: 1
  template:
    metadata:
      labels:
        run: <CONTAINER>
    spec:
      containers:
        - name: <CONTAINER>
          image: <REGISTRY>/<CONTAINER>:<VERSION>
          lifecycle:
            postStart:
              exec:
                command: [
                  "sh /usr/local/bin/init"
                ]
      imagePullSecrets:
        - name: <REGISTRY_SECRET>