apiVersion: v1
kind: Service
metadata:
  namespace: <ENV>
  name: <CONTAINER>
  labels:
    app: <CONTAINER>
spec:
  clusterIP: None
  ports:
    - name: redis
      protocol: TCP
      port: 6379
  selector:
    run: <CONTAINER>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ENV>
  name: <CONTAINER>
spec:
  selector:
    matchLabels:
      run: <CONTAINER>
  replicas: 1
  template:
    metadata:
      labels:
        run: <CONTAINER>
    spec:
      volumes:
        - name: <CONTAINER>-storage
          persistentVolumeClaim:
            claimName: <CONTAINER>-claim
      containers:
        - name: <CONTAINER>
          image: redis:alpine
          ports:
            - containerPort: 6379
          command: ["sh"]
          args: ["-c", "docker-entrypoint.sh --appendonly yes"]
          volumeMounts:
            - mountPath: "/data"
              name: <CONTAINER>-storage
      nodeSelector:
        type: <NODE>
---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: <ENV>
  name: <CONTAINER>-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/var/www/<CONTAINER>"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: <ENV>
  name: <CONTAINER>-claim
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce