apiVersion: v1
kind: Service
metadata:
  namespace: <ENV>
  name: <CONTAINER>
  labels:
    app: <CONTAINER>
spec:
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: 443
  selector:
    run: <CONTAINER>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ENV>
  name: <CONTAINER>
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      run: <CONTAINER>
  replicas: 1
  template:
    metadata:
      labels:
        run: <CONTAINER>
    spec:
      containers:
        - name: <CONTAINER>
          image: <REGISTRY>/<CONTAINER>:<VERSION>
          ports:
            - containerPort: 443

          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /monitoring/alive
              port: 443
            initialDelaySeconds: 15
            failureThreshold: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /monitoring/alive
              port: 443
            initialDelaySeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 15

      imagePullSecrets:
        - name: <REGISTRY_SECRET>