apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ENV>
  name: <CONTAINER>
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      run: <CONTAINER>
  replicas: 1
  template:
    metadata:
      labels:
        run: <CONTAINER>
    spec:
      containers:
        - name: <CONTAINER>
          image: <REGISTRY>/<CONTAINER>:<VERSION>
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          lifecycle:
            postStart:
              exec:
                command: [
                  "/usr/local/bin/init"
                ]
          <OPTIONAL_VOLUME_MOUNT>
            <OPTIONAL_VOLUME_NAME>
              <OPTIONAL_CONTAINER_MOUNT_PATH>

      imagePullSecrets:
        - name: <REGISTRY_SECRET>
      <OPTIONAL_VOLUME>
        <OPTIONAL_VOLUME_NAME>
          <OPTIONAL_VOLUME_HOST_PATH>
            <OPTIONAL_VOLUME_PATH>
      <OPTIONAL_NODE_SELECTOR>
        <OPTIONAL_NODE_TYPE>
