apiVersion: v1
kind: Service
metadata:
  namespace: <ENV>
  name: <CONTAINER>
  labels:
    app: <CONTAINER>
spec:
  clusterIP: None
  ports:
    - name: php-fpm
      protocol: TCP
      port: 9000
  selector:
    run: <CONTAINER>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ENV>
  name: <CONTAINER>
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      run: <CONTAINER>
  replicas: 1
  template:
    metadata:
      labels:
        run: <CONTAINER>
    spec:
      containers:
        - name: <CONTAINER>
          image: <REGISTRY>/<CONTAINER>:<VERSION>
          ports:
            - containerPort: 9000
          readinessProbe:
            exec:
              command:
                - php-fpm-healthcheck # a simple ping since this means it's ready to handle traffic
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - php-fpm-healthcheck
                - --listen-queue-len=128 # fails if there are more than 10 processes waiting in the fpm queue
            initialDelaySeconds: 0
            periodSeconds: 30

          lifecycle:
            postStart:
              exec:
                command: [
                  "/usr/local/bin/init <SCRIPT> <MIGRATE>"
                ]

      imagePullSecrets:
        - name: <REGISTRY_SECRET>