apiVersion: v1
kind: Service
metadata:
  namespace: <ENV>
  name: <CONTAINER>
  labels:
    app: <CONTAINER>
spec:
  clusterIP: None
  ports:
    - name: php-fpm
      protocol: TCP
      port: 9000
  selector:
    run: <CONTAINER>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ENV>
  name: <CONTAINER>
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      run: <CONTAINER>
  replicas: 1
  template:
    metadata:
      labels:
        run: <CONTAINER>
    spec:
      containers:
        - name: <CONTAINER>
          image: <REGISTRY>/<CONTAINER>:<VERSION>
          ports:
            - containerPort: 9000
          lifecycle:
            postStart:
              exec:
                command: [
                  "/bin/sh",
                  "-c",
                  "php /var/www/<DIRECTORY>/artisan config:cache \
                  && php /var/www/<DIRECTORY>/artisan route:cache \
                  && php /var/www/<DIRECTORY>/artisan view:cache \
                  && php /var/www/<DIRECTORY>/artisan <MIGRATE> \
                  && <SCRIPT>
                  "
                ]
      imagePullSecrets:
        - name: <REGISTRY_SECRET>